import { readFileSync } from 'node:fs';
import { ConflictException, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { EnvironmentVariables } from '../../../config/environment.schema.js';
import { SajuChartCalculator } from '../../saju-profiles/saju-chart-calculator.js';
import type { BirthInput } from '../../saju-profiles/saju-profile.contract.js';
import { KasiSolarTermsProvider } from './kasi-solar-terms.provider.js';

// Independent KASI responses (public dates, selected fields), not generated by
// the calculation engine being checked. Provenance: test/fixtures/kasi-sources.md.
const xml2019 = readFileSync(
  new URL(
    '../../../../test/fixtures/kasi-solar-terms-2019.xml',
    import.meta.url,
  ),
  'utf8',
);
const xml2018 = readFileSync(
  new URL(
    '../../../../test/fixtures/kasi-solar-terms-2018.xml',
    import.meta.url,
  ),
  'utf8',
);
const snapshot = (
  month = 3,
  day = 7,
  time: BirthInput['time'] = { precision: 'exact', hour: 12, minute: 0 },
) =>
  new SajuChartCalculator().calculate({
    calendarType: 'solar',
    isLeapMonth: false,
    date: { year: 2019, month, day },
    time,
    luckCycleGender: 'male',
  }).snapshot;

describe('KASI solar terms and natal boundaries', () => {
  const fetchMock = vi.fn<typeof fetch>();
  const provider = (enabled = true) =>
    new KasiSolarTermsProvider(
      new ConfigService<EnvironmentVariables, true>({
        KASI_SOLAR_TERMS_VERIFICATION_ENABLED: enabled,
        KASI_SPECIAL_SERVICE_KEY: 'special+/=',
        KASI_TIMEOUT_MS: 2000,
      }),
    );
  beforeEach(() => {
    vi.spyOn(Logger.prototype, 'debug').mockImplementation(() => undefined);
    vi.spyOn(Logger.prototype, 'warn').mockImplementation(() => undefined);
    vi.stubGlobal('fetch', fetchMock);
    fetchMock.mockReset().mockImplementation(async (input) => {
      if (!(input instanceof URL)) throw new Error('Expected URL');
      return new Response(
        input.searchParams.get('solYear') === '2018' ? xml2018 : xml2019,
      );
    });
  });
  afterEach(() => {
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
  });

  it('uses only the special key and a public year, caches and deduplicates calls', async () => {
    const service = provider();
    const chart = snapshot();
    const results = await Promise.all([
      service.verify(chart),
      service.verify(chart),
    ]);
    expect(results.map(({ status }) => status)).toEqual(['matched', 'matched']);
    await service.verify(chart);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const url = fetchMock.mock.calls[0]![0];
    if (!(url instanceof URL)) throw new Error('Expected URL');
    expect(url.pathname).toBe(
      '/B090041/openapi/service/SpcdeInfoService/get24DivisionsInfo',
    );
    expect(Object.fromEntries(url.searchParams)).toEqual({
      ServiceKey: 'special+/=',
      solYear: '2019',
      numOfRows: '100',
      pageNo: '1',
    });
    vi.spyOn(Date, 'now').mockReturnValue(Date.now() + 86_400_001);
    await service.verify(chart);
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it.each([
    [1, 4],
    [1, 8],
    [2, 3],
    [2, 6],
    [3, 7],
    [3, 21],
    [12, 23],
  ])(
    'checks January, Ipchun, Jie and Zhongqi policies for %i/%i',
    async (month, day) => {
      expect((await provider().verify(snapshot(month, day))).status).toBe(
        'matched',
      );
    },
  );
  it('does not shift the KASI boundary by the birth longitude correction', async () => {
    const chart = snapshot(3, 6, { precision: 'exact', hour: 6, minute: 12 });
    expect(chart.normalizedBirth.timeCorrection?.correctedTime).toEqual({
      hour: 5,
      minute: 42,
    });
    expect((await provider().verify(chart)).status).toBe('matched');
  });
  it('checks the 12 Jie without coercing the official Daehan 1760 typo into a clock', async () => {
    expect(xml2019).toContain('<kst>1760</kst>');
    expect((await provider().verify(snapshot(1, 20))).status).toBe('matched');
  });
  it.each([9, 10, 11])(
    'blocks minute precision ambiguity at 06:%i',
    async (minute) => {
      await expect(
        provider().verify(
          snapshot(3, 6, { precision: 'exact', hour: 6, minute }),
        ),
      ).rejects.toMatchObject({
        response: { reason: 'SAJU_SOLAR_TERM_BOUNDARY_UNCERTAIN' },
      });
    },
  );
  it('does not substitute noon for unknown time, including previously saved boundary charts', async () => {
    const chart = snapshot(3, 6, { precision: 'exact', hour: 12, minute: 0 });
    chart.normalizedBirth.time = { precision: 'unknown' };
    await expect(provider().verify(chart)).rejects.toBeInstanceOf(
      ConflictException,
    );
    expect(
      (await provider().verify(snapshot(3, 7, { precision: 'unknown' })))
        .status,
    ).toBe('matched');
  });
  it('blocks a different pillar caused by disagreement with an official boundary', async () => {
    fetchMock.mockResolvedValue(
      new Response(xml2019.replace('<kst>0610</kst>', '<kst>0640</kst>')),
    );
    const chart = snapshot(3, 6, { precision: 'exact', hour: 6, minute: 20 });
    const before = structuredClone(chart);
    await expect(provider().verify(chart)).rejects.toMatchObject({
      response: { reason: 'SAJU_SOLAR_TERM_MISMATCH' },
    });
    expect(chart).toEqual(before);
  });
  it('rejects a stale snapshot even away from a boundary', async () => {
    const chart = snapshot();
    chart.pillars.month = chart.pillars.year;
    await expect(provider().verify(chart)).rejects.toMatchObject({
      response: { reason: 'SAJU_SOLAR_TERM_MISMATCH' },
    });
  });
  it('skips disabled and unsupported policy charts without fetching', async () => {
    expect((await provider(false).verify(snapshot())).status).toBe('disabled');
    const legacy = snapshot();
    legacy.calculation.policyVersion = 'kr-original-v1';
    expect((await provider().verify(legacy)).status).toBe('unsupported_policy');
    expect(fetchMock).not.toHaveBeenCalled();
  });
  it('reports an empty supported response as no data, without caching a false match', async () => {
    fetchMock.mockResolvedValueOnce(
      new Response(
        '<response><header><resultCode>00</resultCode></header><body><items/><totalCount>0</totalCount></body></response>',
      ),
    );
    const service = provider();
    expect((await service.verify(snapshot())).status).toBe('no_data');
    expect((await service.verify(snapshot())).status).toBe('matched');
  });
  it.each([
    ['wrong year', xml2019.replaceAll('2019', '2020')],
    ['incomplete page', xml2019.replace('<totalCount>24', '<totalCount>10')],
    ['duplicate term', xml2019.replace('<dateName>대한', '<dateName>소한')],
    ['invalid clock', xml2019.replace('<kst>0039', '<kst>2500')],
    [
      'wrong longitude',
      xml2019.replace('<sunLongitude>285', '<sunLongitude>0'),
    ],
    ['wrong date kind', xml2019.replace('<dateKind>03', '<dateKind>01')],
    [
      'entity',
      '<!DOCTYPE response [<!ENTITY x SYSTEM "file:///etc/passwd">]>' + xml2019,
    ],
    ['oversized', ' '.repeat(65_537)],
    ['invalid XML', '<response>'],
    [
      'gateway auth error',
      '<OpenAPI_ServiceResponse><returnReasonCode>30</returnReasonCode></OpenAPI_ServiceResponse>',
    ],
  ])('does not trust %s', async (_name, xml) => {
    fetchMock.mockResolvedValue(new Response(xml));
    expect((await provider().verify(snapshot())).status).toBe('unavailable');
  });
  it('normalizes HTTP failure and timeout without a retry', async () => {
    fetchMock.mockResolvedValueOnce(new Response('private', { status: 403 }));
    const service = provider();
    expect((await service.verify(snapshot())).status).toBe('unavailable');
    fetchMock.mockRejectedValueOnce(
      new DOMException('private', 'TimeoutError'),
    );
    expect((await service.verify(snapshot())).status).toBe('unavailable');
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });
});
